# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ff7f76b
_src_path: gh:scipp/copier_template
description: Data reduction for NMX at the European Spallation Source
max_python: '3.11'
min_python: '3.9'
namespace_package: ess
nightly_deps: scipp,sciline,scippnexus,plopp
orgname: scipp
prettyname: Essnmx
projectname: essnmx
related_projects: Scipp,Sciline,Plopp,ScippNexus
year: 2023
